version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/pokedex/Dockerfile
    ports:
      - 3001:3000
    networks:
      - local
  pokedex-redux:
    container_name: pokedex-redux
    build:
      context: .
      dockerfile: ./apps/pokedex-redux/Dockerfile
    ports:
      - 3000:3000
    networks:
      - local

networks:
  local:
